version: "3.1"

services:
  jenkins:
          image: 51.140.125.101/admin/jenkins:1
          deploy:
              mode: replicated
              replicas: 1
          ports:
              - 30010:8080
              - 50000:50000
          volumes:
              - jenkins:/var/jenkins_home
volumes:
        jenkins:

