version: "3.3"

services:
  jenkins:
      image: 52.56.228.3/admin/jenkins:2.82-alpine
      deploy:
          mode: replicated
          replicas: 1
          placement:
              constraints:
                  - 'node.platform.os == linux'
      networks:
          - default
      ports:
          - 30000:8080
          - 50000:50000
      volumes:
          - jenkins:/var/jenkins_home
volumes:
    jenkins:

networks:
    default:
